Implement Redux Toolkit inside of a React application
fickryiman/bookstore-cms-rep pull request #2
Opened 2023-07-17 15:12 UTC by fickryiman

Setup a Redux store
Create a slice to save your state and reducers
- Add Redux Toolkit (npm install react-redux @reduxjs/toolkit)
- Create a directory that will contain all your Redux logic (/src/redux)
- Configure a Redux store (/src/redux/store.js)
- Define a slice of state for books that: Includes an array of books (initial state: empty array) Includes a reducer that adds a book
Includes a reducer that removes a book
- Define a slice of state for categories that: Includes an array of categories (initial state: empty array) Includes a reducer that checks the status and always returns "Under construction" (the initial state should check to that string)
- Structure the application files using a "feature folder" approach and use the ducks pattern for the Redux files.

2023-07-17 16:51 UTC, souad988 requested changes
Hi @fickryiman , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![242722065-db428b0c-8dfc-49c4-a156-42f227e32868](https://github.com/fickryiman/bookstore-cms-rep/assets/59707859/8e93f1c5-0990-47f4-a489-3ec03661c274)


## Highlights
Good PR description
Good file structure
Correct store configuration
Professional README

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-17 16:51 UTC, souad988 commented on src/redux/books/bookSlice.js
> +      state.bookItems.push(bookId);
great work was done so far, I want just to mention that we can't manipulate the state directly but asign a new object or array to it "
For redux to work correctly, the state must be immutable. This means that whenever we update the redux state, we have to create a copy of the whole state and set values to fields we want to change"  

also addBook is meant to receive data needed to create a new Book object so the correct way to implement it can be : 
````javascript
addBook: (state, action) => {
      state.books = [
        ...state.books,
        {
          id: Math.floor(Math.random() * 100),
          title: action.payload.title,
          author: action.payload.author,
        },
      ]
    },
````

2023-07-17 16:51 UTC, souad988 commented on src/redux/categories/categorySlice.js
> +    }),
In the project requirements "Includes an array of categories (initial state: empty array)
Includes a reducer that checks the status and always returns "Under construction" (the initial state should check to that string)
"
the idea is check status checks the status received in the payload and update the state accordingly 

````javascript
     state.categories =
        action.payload === "Under construction"
          ? "Under construction"
          : state.categories
    },
````

2023-07-18 02:15 UTC, fickryiman commented on src/redux/books/bookSlice.js
> +      state.bookItems.push(bookId);
ok, created a copy of the whole bookstore state

2023-07-18 03:13 UTC, Davidosky007 approved these changes
Hi @fickryiman 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Well written PR 👍 
* Good looking readme 👍 
* Redux setup properly 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 03:25 UTC, merged